/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculator */

#ifndef _Included_Calculator
#define _Included_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculator
 * Method:    Calculate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Calculator_Calculate
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
